name: unit test
on:
  push:
    branches:
      - main

jobs:
  unit_tests_nightly_pytorch:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          miniconda-version: latest
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: 'set -eux

          conda activate test

          pip install -r requirements.txt

          pip install -r dev-requirements.txt

          pip install  --no-build-isolation -e .

          conda install pytorch cpuonly -c pytorch-nightly

          '
        shell: bash -l {0}
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Run unit tests with coverage
        run: 'set -eux

          conda activate test

          pytest --cov=. --cov-report xml tests -vv

          '
        shell: bash -l {0}
      - id: measurement-6
        name: Record Measurement After Run unit tests with coverage
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run unit tests with coverage
          task: get-measurement
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740222587.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740222587.json
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
  unit_tests_stable_pytorch:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          miniconda-version: latest
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: 'set -eux

          conda activate test

          pip install -r requirements.txt

          pip install -r dev-requirements.txt

          pip install  --no-build-isolation -e .

          '
        shell: bash -l {0}
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Run unit tests with coverage
        run: 'set -eux

          conda activate test

          pytest --cov=. --cov-report xml tests -vv

          '
        shell: bash -l {0}
      - id: measurement-6
        name: Record Measurement After Run unit tests with coverage
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run unit tests with coverage
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740222587.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740222587.json
    strategy:
      matrix:
        python-version:
          - 3.8
